-- Business Logic Functions
-- Module: Purchase Orders
-- Description: Purchase order create, submit, approve workflow
-- Author: happyveggie & Claude Opus 4.5

-- =============================================================================
-- HELPER FUNCTION: Validate PO Status Transition
-- =============================================================================
-- Validates that a status transition is allowed

CREATE OR REPLACE FUNCTION validate_po_status_transition(
    p_current_status VARCHAR,
    p_new_status VARCHAR
)
RETURNS BOOLEAN AS $$
DECLARE
    v_valid_transitions JSONB := '{
        "draft": ["submitted", "cancelled"],
        "submitted": ["approved", "rejected", "cancelled"],
        "approved": ["partially_received", "fully_received", "cancelled"],
        "rejected": ["draft"],
        "partially_received": ["fully_received"],
        "fully_received": [],
        "cancelled": []
    }'::JSONB;
    v_allowed TEXT[];
BEGIN
    -- Get allowed transitions for current status
    SELECT ARRAY(SELECT jsonb_array_elements_text(v_valid_transitions -> p_current_status))
    INTO v_allowed;

    -- Check if new status is in allowed list
    RETURN p_new_status = ANY(v_allowed);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON FUNCTION validate_po_status_transition(VARCHAR, VARCHAR) IS 'Validates PO status transitions';

-- =============================================================================
-- FUNCTION: Create Purchase Order
-- =============================================================================
-- Creates a new purchase order with line items

CREATE OR REPLACE FUNCTION create_purchase_order(
    p_user_id UUID,
    p_supplier_id UUID,
    p_po_date DATE DEFAULT CURRENT_DATE,
    p_expected_delivery_date DATE DEFAULT NULL,
    p_currency VARCHAR DEFAULT 'USD',
    p_notes TEXT DEFAULT NULL,
    p_lines JSONB DEFAULT '[]'::JSONB
)
RETURNS JSONB AS $$
DECLARE
    v_po_id UUID;
    v_po_number VARCHAR;
    v_total_amount DECIMAL(15,2) := 0;
    v_line JSONB;
    v_line_number INTEGER := 0;
    v_line_total DECIMAL(15,2);
    v_line_id UUID;
BEGIN
    -- Validate user has create permission
    IF NOT can_user_perform_action(p_user_id, 'purchase_order', 'create') THEN
        RAISE EXCEPTION 'User does not have permission to create purchase orders';
    END IF;

    -- Validate supplier exists and is active
    IF NOT EXISTS (
        SELECT 1 FROM suppliers
        WHERE supplier_id = p_supplier_id
          AND is_active = TRUE
          AND is_deleted = FALSE
    ) THEN
        RAISE EXCEPTION 'Invalid or inactive supplier: %', p_supplier_id;
    END IF;

    -- Validate at least one line item
    IF jsonb_array_length(p_lines) = 0 THEN
        RAISE EXCEPTION 'Purchase order must have at least one line item';
    END IF;

    -- Generate PO ID
    v_po_id := gen_random_uuid();

    -- Create the purchase order (po_number will be auto-generated by trigger)
    INSERT INTO purchase_orders (
        po_id,
        supplier_id,
        po_date,
        expected_delivery_date,
        currency,
        total_amount,
        status,
        notes,
        created_by,
        created_at
    ) VALUES (
        v_po_id,
        p_supplier_id,
        p_po_date,
        p_expected_delivery_date,
        p_currency,
        0,  -- Will be updated after lines
        'draft',
        p_notes,
        p_user_id,
        NOW()
    )
    RETURNING po_number INTO v_po_number;

    -- Create line items
    FOR v_line IN SELECT * FROM jsonb_array_elements(p_lines)
    LOOP
        v_line_number := v_line_number + 1;
        v_line_id := gen_random_uuid();

        -- Calculate line total
        v_line_total := COALESCE((v_line->>'quantity_ordered')::DECIMAL, 0) *
                       COALESCE((v_line->>'unit_price')::DECIMAL, 0);

        INSERT INTO purchase_order_lines (
            line_id,
            po_id,
            line_number,
            item_code,
            item_description,
            quantity_ordered,
            quantity_received,
            quantity_invoiced,
            uom,
            unit_price,
            line_total,
            created_at
        ) VALUES (
            v_line_id,
            v_po_id,
            v_line_number,
            COALESCE(v_line->>'item_code', 'ITEM-' || v_line_number),
            v_line->>'item_description',
            COALESCE((v_line->>'quantity_ordered')::DECIMAL, 0),
            0,
            0,
            COALESCE(v_line->>'uom', 'EA'),
            COALESCE((v_line->>'unit_price')::DECIMAL, 0),
            v_line_total,
            NOW()
        );

        v_total_amount := v_total_amount + v_line_total;
    END LOOP;

    -- Update total amount on PO
    UPDATE purchase_orders
    SET total_amount = v_total_amount,
        updated_at = NOW()
    WHERE po_id = v_po_id;

    -- Return the created PO
    RETURN jsonb_build_object(
        'success', TRUE,
        'po_id', v_po_id,
        'po_number', v_po_number,
        'total_amount', v_total_amount,
        'line_count', v_line_number,
        'status', 'draft',
        'message', 'Purchase order created successfully'
    );

EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object(
        'success', FALSE,
        'error', SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION create_purchase_order(UUID, UUID, DATE, DATE, VARCHAR, TEXT, JSONB) IS 'Creates a new purchase order with line items';

-- =============================================================================
-- FUNCTION: Submit Purchase Order
-- =============================================================================
-- Submits a draft PO for approval

CREATE OR REPLACE FUNCTION submit_purchase_order(
    p_user_id UUID,
    p_po_id UUID
)
RETURNS JSONB AS $$
DECLARE
    v_current_status VARCHAR;
    v_po_record RECORD;
    v_line_count INTEGER;
BEGIN
    -- Validate user has submit permission
    IF NOT can_user_perform_action(p_user_id, 'purchase_order', 'submit') THEN
        RAISE EXCEPTION 'User does not have permission to submit purchase orders';
    END IF;

    -- Get current PO state
    SELECT po_id, po_number, status, total_amount, created_by
    INTO v_po_record
    FROM purchase_orders
    WHERE po_id = p_po_id
      AND is_deleted = FALSE;

    IF v_po_record IS NULL THEN
        RAISE EXCEPTION 'Purchase order not found: %', p_po_id;
    END IF;

    v_current_status := v_po_record.status;

    -- Validate status transition
    IF NOT validate_po_status_transition(v_current_status, 'submitted') THEN
        RAISE EXCEPTION 'Cannot submit PO with status: %', v_current_status;
    END IF;

    -- Validate PO has line items
    SELECT COUNT(*) INTO v_line_count
    FROM purchase_order_lines
    WHERE po_id = p_po_id
      AND is_deleted = FALSE;

    IF v_line_count = 0 THEN
        RAISE EXCEPTION 'Cannot submit PO without line items';
    END IF;

    -- Validate total amount is greater than 0
    IF v_po_record.total_amount <= 0 THEN
        RAISE EXCEPTION 'Cannot submit PO with zero or negative amount';
    END IF;

    -- Update status
    UPDATE purchase_orders
    SET status = 'submitted',
        submitted_at = NOW(),
        submitted_by = p_user_id,
        updated_at = NOW(),
        updated_by = p_user_id
    WHERE po_id = p_po_id;

    RETURN jsonb_build_object(
        'success', TRUE,
        'po_id', p_po_id,
        'po_number', v_po_record.po_number,
        'old_status', v_current_status,
        'new_status', 'submitted',
        'message', 'Purchase order submitted for approval'
    );

EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object(
        'success', FALSE,
        'error', SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION submit_purchase_order(UUID, UUID) IS 'Submits a purchase order for approval';

-- =============================================================================
-- FUNCTION: Approve Purchase Order
-- =============================================================================
-- Approves a submitted PO

CREATE OR REPLACE FUNCTION approve_purchase_order(
    p_user_id UUID,
    p_po_id UUID,
    p_approval_notes TEXT DEFAULT NULL
)
RETURNS JSONB AS $$
DECLARE
    v_current_status VARCHAR;
    v_po_record RECORD;
BEGIN
    -- Validate user has approve permission
    IF NOT can_user_perform_action(p_user_id, 'purchase_order', 'approve') THEN
        RAISE EXCEPTION 'User does not have permission to approve purchase orders';
    END IF;

    -- Get current PO state
    SELECT po_id, po_number, status, total_amount, created_by
    INTO v_po_record
    FROM purchase_orders
    WHERE po_id = p_po_id
      AND is_deleted = FALSE;

    IF v_po_record IS NULL THEN
        RAISE EXCEPTION 'Purchase order not found: %', p_po_id;
    END IF;

    v_current_status := v_po_record.status;

    -- Validate status transition
    IF NOT validate_po_status_transition(v_current_status, 'approved') THEN
        RAISE EXCEPTION 'Cannot approve PO with status: %. Must be submitted first.', v_current_status;
    END IF;

    -- Prevent self-approval (user cannot approve their own PO)
    IF v_po_record.created_by = p_user_id THEN
        -- Check if self-approval is allowed (could be configurable)
        -- For now, we'll allow it but could add a config check here
        NULL;
    END IF;

    -- Update status
    UPDATE purchase_orders
    SET status = 'approved',
        approved_at = NOW(),
        approved_by = p_user_id,
        approval_notes = p_approval_notes,
        updated_at = NOW(),
        updated_by = p_user_id
    WHERE po_id = p_po_id;

    RETURN jsonb_build_object(
        'success', TRUE,
        'po_id', p_po_id,
        'po_number', v_po_record.po_number,
        'old_status', v_current_status,
        'new_status', 'approved',
        'approved_by', p_user_id,
        'message', 'Purchase order approved'
    );

EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object(
        'success', FALSE,
        'error', SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION approve_purchase_order(UUID, UUID, TEXT) IS 'Approves a submitted purchase order';

-- =============================================================================
-- FUNCTION: Reject Purchase Order
-- =============================================================================
-- Rejects a submitted PO

CREATE OR REPLACE FUNCTION reject_purchase_order(
    p_user_id UUID,
    p_po_id UUID,
    p_rejection_reason TEXT
)
RETURNS JSONB AS $$
DECLARE
    v_current_status VARCHAR;
    v_po_record RECORD;
BEGIN
    -- Validate user has approve permission (same permission for reject)
    IF NOT can_user_perform_action(p_user_id, 'purchase_order', 'approve') THEN
        RAISE EXCEPTION 'User does not have permission to reject purchase orders';
    END IF;

    -- Validate rejection reason is provided
    IF p_rejection_reason IS NULL OR TRIM(p_rejection_reason) = '' THEN
        RAISE EXCEPTION 'Rejection reason is required';
    END IF;

    -- Get current PO state
    SELECT po_id, po_number, status
    INTO v_po_record
    FROM purchase_orders
    WHERE po_id = p_po_id
      AND is_deleted = FALSE;

    IF v_po_record IS NULL THEN
        RAISE EXCEPTION 'Purchase order not found: %', p_po_id;
    END IF;

    v_current_status := v_po_record.status;

    -- Validate status transition
    IF NOT validate_po_status_transition(v_current_status, 'rejected') THEN
        RAISE EXCEPTION 'Cannot reject PO with status: %', v_current_status;
    END IF;

    -- Update status
    UPDATE purchase_orders
    SET status = 'rejected',
        rejected_at = NOW(),
        rejected_by = p_user_id,
        rejection_reason = p_rejection_reason,
        updated_at = NOW(),
        updated_by = p_user_id
    WHERE po_id = p_po_id;

    RETURN jsonb_build_object(
        'success', TRUE,
        'po_id', p_po_id,
        'po_number', v_po_record.po_number,
        'old_status', v_current_status,
        'new_status', 'rejected',
        'rejected_by', p_user_id,
        'rejection_reason', p_rejection_reason,
        'message', 'Purchase order rejected'
    );

EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object(
        'success', FALSE,
        'error', SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION reject_purchase_order(UUID, UUID, TEXT) IS 'Rejects a submitted purchase order';

-- =============================================================================
-- FUNCTION: Cancel Purchase Order
-- =============================================================================
-- Cancels a PO (if allowed by current status)

CREATE OR REPLACE FUNCTION cancel_purchase_order(
    p_user_id UUID,
    p_po_id UUID,
    p_cancellation_reason TEXT
)
RETURNS JSONB AS $$
DECLARE
    v_current_status VARCHAR;
    v_po_record RECORD;
BEGIN
    -- Validate user has delete/cancel permission
    IF NOT can_user_perform_action(p_user_id, 'purchase_order', 'delete') THEN
        RAISE EXCEPTION 'User does not have permission to cancel purchase orders';
    END IF;

    -- Get current PO state
    SELECT po_id, po_number, status
    INTO v_po_record
    FROM purchase_orders
    WHERE po_id = p_po_id
      AND is_deleted = FALSE;

    IF v_po_record IS NULL THEN
        RAISE EXCEPTION 'Purchase order not found: %', p_po_id;
    END IF;

    v_current_status := v_po_record.status;

    -- Validate status transition
    IF NOT validate_po_status_transition(v_current_status, 'cancelled') THEN
        RAISE EXCEPTION 'Cannot cancel PO with status: %. PO may have been received.', v_current_status;
    END IF;

    -- Update status
    UPDATE purchase_orders
    SET status = 'cancelled',
        cancelled_at = NOW(),
        cancelled_by = p_user_id,
        cancellation_reason = p_cancellation_reason,
        updated_at = NOW(),
        updated_by = p_user_id
    WHERE po_id = p_po_id;

    RETURN jsonb_build_object(
        'success', TRUE,
        'po_id', p_po_id,
        'po_number', v_po_record.po_number,
        'old_status', v_current_status,
        'new_status', 'cancelled',
        'message', 'Purchase order cancelled'
    );

EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object(
        'success', FALSE,
        'error', SQLERRM
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION cancel_purchase_order(UUID, UUID, TEXT) IS 'Cancels a purchase order';

-- =============================================================================
-- FUNCTION: Update PO Line Quantities (Internal)
-- =============================================================================
-- Updates received/invoiced quantities on PO lines

CREATE OR REPLACE FUNCTION update_po_line_quantities(
    p_po_id UUID,
    p_update_type VARCHAR  -- 'received' or 'invoiced'
)
RETURNS VOID AS $$
DECLARE
    v_all_complete BOOLEAN;
    v_any_received BOOLEAN;
    v_new_status VARCHAR;
BEGIN
    IF p_update_type = 'received' THEN
        -- Update quantity_received on each line from goods receipts
        UPDATE purchase_order_lines pol
        SET quantity_received = COALESCE((
            SELECT SUM(grl.quantity_received)
            FROM goods_receipt_lines grl
            JOIN goods_receipts gr ON grl.gr_id = gr.gr_id
            WHERE grl.po_line_id = pol.line_id
              AND gr.is_deleted = FALSE
              AND grl.is_deleted = FALSE
        ), 0);

        -- Check if all lines are fully received
        SELECT
            NOT EXISTS (
                SELECT 1 FROM purchase_order_lines
                WHERE po_id = p_po_id
                  AND quantity_received < quantity_ordered
                  AND is_deleted = FALSE
            ),
            EXISTS (
                SELECT 1 FROM purchase_order_lines
                WHERE po_id = p_po_id
                  AND quantity_received > 0
                  AND is_deleted = FALSE
            )
        INTO v_all_complete, v_any_received;

        -- Update PO status based on receipt status
        IF v_all_complete THEN
            v_new_status := 'fully_received';
        ELSIF v_any_received THEN
            v_new_status := 'partially_received';
        ELSE
            v_new_status := NULL;  -- No change
        END IF;

        IF v_new_status IS NOT NULL THEN
            UPDATE purchase_orders
            SET status = v_new_status,
                updated_at = NOW()
            WHERE po_id = p_po_id
              AND status IN ('approved', 'partially_received');
        END IF;

    ELSIF p_update_type = 'invoiced' THEN
        -- Update quantity_invoiced on each line from invoice lines
        UPDATE purchase_order_lines pol
        SET quantity_invoiced = COALESCE((
            SELECT SUM(il.quantity)
            FROM invoice_lines il
            JOIN invoice_receipts ir ON il.invoice_id = ir.invoice_id
            WHERE il.po_line_id = pol.line_id
              AND ir.is_deleted = FALSE
              AND il.is_deleted = FALSE
        ), 0);
    END IF;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION update_po_line_quantities(UUID, VARCHAR) IS 'Updates PO line quantities from receipts/invoices';

-- =============================================================================
-- EXAMPLES AND TESTS
-- =============================================================================

/*
-- Create a purchase order
SELECT create_purchase_order(
    '00000000-0000-0000-0000-000000000100'::UUID,  -- user_id
    (SELECT supplier_id FROM suppliers LIMIT 1),   -- supplier_id
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '14 days',
    'USD',
    'Test PO',
    '[
        {"item_code": "WIDGET-001", "item_description": "Blue Widget", "quantity_ordered": 100, "unit_price": 10.00, "uom": "EA"},
        {"item_code": "GADGET-002", "item_description": "Red Gadget", "quantity_ordered": 50, "unit_price": 25.00, "uom": "EA"}
    ]'::JSONB
);

-- Submit the PO
SELECT submit_purchase_order(
    '00000000-0000-0000-0000-000000000100'::UUID,
    (SELECT po_id FROM purchase_orders ORDER BY created_at DESC LIMIT 1)
);

-- Approve the PO
SELECT approve_purchase_order(
    '00000000-0000-0000-0000-000000000100'::UUID,
    (SELECT po_id FROM purchase_orders ORDER BY created_at DESC LIMIT 1),
    'Approved for Q1 procurement'
);
*/
